### ISSUE TITLE
Unix socket missing

### ISSUE THREAD

**Issue by bkmeneguello** [aptalca/docker-zoneminder#11]
After configuring my first RTSP camera, I'm receiving lots of errors like

    Nov  4 16:47:58 5ae1f16bfbbd web_php[548]: ERR [socket_sendto( /var/run/zm/zms-464073s.sock ) failed: No such file or directory]
    Nov  4 16:47:58 5ae1f16bfbbd web_php[729]: ERR [getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-464073s.sock ) failed: No such file or directory - checkStreamForErrors()]

May be related to [this bug](https://bugs.launchpad.net/ubuntu/+source/zoneminder/+bug/1159361)?

**Comment by aptalca** [comment]
Could be, not sure. In any case, it seems to be a zoneminder bug. You should ask on their forums.

I really only make the docker container for it. I refer zoneminder specific issues to their team.

**Comment by jangeador** [comment]
I got this error as well. Try changing the path in `options/paths` in the `PATH_ZMS` setting from `/cgi-bin/nph-zms` to `/zm/cgi-bin/nph-zms`. That took care of this error for me.

**Comment by spyderdyne** [comment]
Didn't work for me.  See issue 14.
