### ISSUE TITLE
Zoneminder CGI on LXC/LXD not usable on 1.30.4

### ISSUE THREAD

**Issue by spyderdyne** [aptalca/docker-zoneminder#14]
ISSUE:
Stills but no UI vdeo streams and empty events and blank streams.

ERROR:
[Mon Aug 28 22:52:23.732261 2017] [:error] [pid 17138] [client 192.168.170.58:58797] ERR [Socket /var/run/zm/zms-581052s.sock does not exist.  This file is created by zms, and since it does not exist, either zms did not run, or zms exited early.  Please check your zms logs and ensure that CGI is enabled in apache and check that the PATH_ZMS is set correctly.  Make sure that ZM is actually recording.  If you are trying to view a live stream and the capture process (zmc) is not running then zms will exit. Please go to http://zoneminder.readthedocs.io/en/latest/faq.html#why-can-t-i-see-streamed-images-when-i-can-see-stills-in-the-zone-window-etc for more information.], referer: http://192.168.110.245/zm/?view=montage&group=0

The help text doesn't seem to resolve this issue.

Apache zoneminder.conf:
root@zoneminder:/var/log/zm# cat /etc/apache2/conf-enabled/zoneminder.conf 

Remember to enable cgi mod (i.e. "a2enmod cgi").
ScriptAlias /zm/cgi-bin "/usr/lib/zoneminder/cgi-bin"
<Directory > "/usr/lib/zoneminder/cgi-bin"

CGI paths:
root@zoneminder:/var/log/zm# ls /usr/lib/zoneminder/cgi-bin/ 
nph-zms  zms

UI Path Setting:
PATH_ZMS /zm/cgi-bin/nph-zms

Empty ZM Sockets, no ZMC:
root@zoneminder:/var/log/zm# ls -al /var/run/zm*
total 4
drwxr-xr-x  2 www-data www-data 220 Aug 28 22:52 .
drwxr-xr-x 21 root     root     740 Aug 28 06:25 ..
-rw-r--r--  1 www-data www-data   5 Aug 28 22:50 zm.pid
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:50 zmcontrol-1.sock
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:25 zmcontrol-2.sock
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:50 zmdc.sock
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:50 zmf-1.sock
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:50 zmf-2.sock
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:50 zmf-3.sock
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:50 zmf-4.sock
srwxr-xr-x  1 www-data www-data   0 Aug 28 22:50 zmtrigger.sock

ZM Not Logging to proper directory by default:
root@zoneminder:/var/log/zm# ls -al
total 12
drwxr-xr-x 2 www-data root    2 Aug 28 22:14 .
drwxrwxr-x 9 root     syslog 22 Aug 28 21:59 ..
root@zoneminder:/var/log/zm# pwd
/var/log/zm

Ubuntu Xenial, static RFC1918 IP address, portal fully functional but no video.  Here is my config for the cameras:

[https://forums.zoneminder.com/viewtopic.php?f=34&t=26190&p=102103#p102103](url)

What???

**Comment by spyderdyne** [comment]
ZMNinja unable to discover it either...

**Comment by spyderdyne** [comment]
Mapping host /dev/shm doesn't help.

<url>https://forums.zoneminder.com/viewtopic.php?f=34&t=25609&p=102105#p102105</url>

root@ayana-angel:~# df -m /var/lib/lxd/devices/zoneminder/disk.dev-shm/
Filesystem     1M-blocks  Used Available Use% Mounted on
tmpfs               8008   199      7809   3% /var/lib/lxd/devices/zoneminder/disk.dev-shm
root@ayana-angel:~# df -m /dev/shm
Filesystem     1M-blocks  Used Available Use% Mounted on
tmpfs               8008   199      7809   3% /dev/shm

**Comment by aptalca** [comment]
I didn't publish a 1.30 container, only 1.28 and 1.29

Also I'm not sure what lxc or lxd has to do with this. This is a docker container
