### ISSUE TITLE
Update to version with API?

### ISSUE THREAD

**Issue by kylerw** [aptalca/docker-zoneminder#5]
Want to run zmNinja and need APIs.

**Comment by aptalca** [comment]
When 1.29 is released in the stable PPA your container should automatically update

**Comment by aptalca** [comment]
If you want to use the release candidate, you can upgrade it manually in the meantime.

Enter the container with `docker exec -it Zoneminder bash`
Stop the zoneminder service with `service zoneminder stop`
Follow the rest of the process listed here: https://github.com/pliablepixels/zmNinja/wiki/Easy-Way:-Upgrading-from-non-API-package-to-API-package

Keep in mind that I haven't tested it, so you're in uncharted waters here
