### ISSUE TITLE
ZoneMinder web GUI uses path "/cgi-bin/..." which is not ZM's CGI directory

### ISSUE THREAD

**Issue by C-Duv** [aptalca/docker-zoneminder#7]
In the ZoneMinder web GUI, the path `/cgi-bin/...` is used: eg. `/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=1&connkey=575707&rand=1458139300` when trying to live display a monitor (on the `index.php?view=watch&mid=1` page).
But this path (`/cgi-bin`) is a _ScriptAlias_ to `/usr/lib/cgi-bin/` as per `/etc/apache2/conf-available/serve-cgi-bin.conf` file.

I can see the  `/etc/apache2/conf-available/serve-cgi-bin.conf` file declares a `/zm/cgi-bin` _ScriptAlias_ to `/usr/lib/zoneminder/cgi-bin`.

Part of the problem is the upstream ZoneMinder not following it's current base directory (accessing via `/foobar-zm` should make it try to use `/foobar-zm/cgi-bin`)?

A solution would be to disable Apache's built-in `/cgi-bin` _ScriptAlias_ and change the ZM's one to `/cgi-bin` instead of `/zm/cgi-bin`.

**Comment by aptalca** [comment]
Is this regarding v1.29? If so,  you need to change the PATH_ZMS to /zm/cgi-bin/nph-zms in zoneminder settings. It's in the docker description

**Comment by C-Duv** [comment]
Yes, I'm on v1.29.
Thanks, setting `PATH_ZMS` to _/zm/cgi-bin/nph-zms_ seems to do the trick.
(I must have read the _master_ documentation not the _v1.29_'s branch).

**Comment by zcworld** [comment]
for me .. it still got that error
so its a simple fix 

log in as root to the server
cd /usr/lib/cgi-bin
cp -r /usr/lib/zoneminder/cgi-bin/* ./
chown -R www-data:www-data ./

Job Done, ZM will display images
