### ISSUE TITLE
Storage location

### ISSUE THREAD

**Issue by thesimonho** [aptalca/docker-zoneminder#9]
Where does ZM store recorded footage/images? I'm guessing that currently its all stored within the container or in the config location?

Would it be possible to add a new volume mapping option to have the large files that ZM creates stored on some other drive?

I have this installed through unraid with the config directory set as my SSD. My concern is that space on the SSD will be filled very quickly if many ZM events are stored, and would prefer to set the storage location to one of the data shares instead

**Comment by aptalca** [comment]
They are stored in the config folder under /events I believe. 

Unraid user shares don't play well with hardlinks. But you can change the config folder location to a disk share

**Comment by maskott** [comment]
@aptalca Where might one change the config folder location? I've been searching everywhere to no avail. Thanks!
